name: Python CI

on:
  push:
    branches: [ master, main ] # Adjust if your default branch has a different name
  pull_request:
    branches: [ master, main ] # Adjust if your default branch has a different name

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # if requirements.txt existed, you would add:
        # pip install -r requirements.txt

    - name: Run unit tests
      run: python -m unittest discover -v

    - name: Run script (basic integration test)
      run: |
        echo "This is a test file for pnger." > original.txt
        python pnger.py -i original.txt -o test.png
        python pnger.py -i test.png -o recovered.txt -u
        diff original.txt recovered.txt
